galaxy_info:
  min_ansible_version: 2.1
  platforms:
  - name: Fedora
    versions:
    - 38
    - 39
    - 40
  - name: Ubuntu
    versions:
    - focal
    - jammy
    - noble

  galaxy_tags: []

dependencies: []
